# For Fleet Free: 
# - This file updates policies, queries, agent_options, and controls for all hosts.

# For Fleet Premium:
# - This file updates policies and queries that run on all hosts ("All teams"). 
# - Remove "controls" and add this to your YAML files in teams/ instead.

policies:
queries:
agent_options:
  path: ./lib/agent-options.yml
controls:
org_settings:
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: Nasty Randy's Feline Emporium
  webhook_settings:
    activities_webhook:
      enable_activities_webhook: true
      destination_url: https://webhook.site/86c80a90-3ef9-408d-9173-71eb4cffe39c
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
  fleet_desktop:
    transparency_url: https://catoftheday.com
  host_expiry_settings:
    host_expiry_enabled: false
    host_expiry_window: 30
